### ISSUE TITLE
Modprobe Parse Error

### ISSUE THREAD

**Issue by travankor** [anatol/booster#78]
I'm seeing this after upgrading to booster 0.4, with this commit specifically https://github.com/anatol/booster/commit/355b308bb7fded957c6dab1d81a8a9eed3d3fffb.

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
main.parseModprobe(0xc00107e2c0, 0x2be, 0xc0000c5a78, 0xc00107e2c0, 0x2be)
        /builddir/booster-0.4/_build-booster-xbps/src/github.com/anatol/booster/generator/kmod.go:731 +0x5dc
main.readModprobeOptions(0xc000bfd650, 0x0, 0x0)
        /builddir/booster-0.4/_build-booster-xbps/src/github.com/anatol/booster/generator/kmod.go:788 +0x479
main.NewKmod(0xc0000dc360, 0x1, 0x0, 0x0)
        /builddir/booster-0.4/_build-booster-xbps/src/github.com/anatol/booster/generator/kmod.go:77 +0x24f
main.(*Image).appendModules(0xc0000be480, 0xc0000dc360, 0x0, 0x0, 0x0)
        /builddir/booster-0.4/_build-booster-xbps/src/github.com/anatol/booster/generator/generator.go:196 +0x45
main.generateInitRamfs(0xc0000dc360, 0x0, 0x0)
        /builddir/booster-0.4/_build-booster-xbps/src/github.com/anatol/booster/generator/generator.go:100 +0x1ce
main.runGenerator(0x0, 0x0)
        /builddir/booster-0.4/_build-booster-xbps/src/github.com/anatol/booster/generator/main.go:73 +0x105
main.main()
        /builddir/booster-0.4/_build-booster-xbps/src/github.com/anatol/booster/generator/main.go:85 +0x8a
```

**Comment by anatol** [comment]
Thanks for the report. It should be fixed now. Please try `master` branch and let me know if you still see any issue.
