### ISSUE TITLE
booster-git aur build error due to make-dependency ruby gem mini_portile2 version (needs 2.5.0 but arch is currently on 2.6.1-1)

### ISSUE THREAD

**Issue by CarbonChauvinist** [anatol/booster#91]
Been using booster-git from aur. Currently unable to build latest commit `0.5.r5.g6afd40e-1` due to a build error. AFAICT, it needs to have the ruby gem `mini_portile2 2.5.0` but arch is currently at `2.6.1-1` which is provided as a depend for `ruby-nokogiri` which itself is a dependency of the make-depend `ruby-ronn-ng`?

````
Running aur chroot --update -D /home/ghost/chroot --pacman-conf /etc/aurutils/pacman-aur.conf
:: Synchronizing package databases...
 core is up to date
 extra                                                                                             1565.1 KiB  5.66 MiB/s 00:00 [#############################################################################] 100%
 community                                                                                            5.6 MiB  18.2 MiB/s 00:00 [#############################################################################] 100%
 aur is up to date
:: Starting full system upgrade...
 there is nothing to do
Running aur chroot --packagelist -D /home/ghost/chroot --pacman-conf /etc/aurutils/pacman-aur.conf
Running aur chroot --build -D /home/ghost/chroot --pacman-conf /etc/aurutils/pacman-aur.conf -- -c -u --
==> Synchronizing chroot copy [/home/ghost/chroot/root] -> [ghost]...done
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 aur is up to date
:: Starting full system upgrade...
 there is nothing to do
==> Making package: booster-git 0.5.r5.g6afd40e-1 (Thu Jun 10 05:58:45 2021)
...
...
Checked in 'GEM_PATH=/build/.local/share/gem/ruby/3.0.0:/usr/lib/ruby/gems/3.0.0' at: /usr/lib/ruby/gems/3.0.0/specifications/nokogiri-1.11.7.gemspec, execute `gem env` for more information
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1401:in `block in activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1390:in `each'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1390:in `activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1372:in `activate'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1408:in `block in activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1390:in `each'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1390:in `activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1372:in `activate'
        from /usr/lib/ruby/3.0.0/rubygems.rb:302:in `block in activate_bin_path'
        from /usr/lib/ruby/3.0.0/rubygems.rb:301:in `synchronize'
        from /usr/lib/ruby/3.0.0/rubygems.rb:301:in `activate_bin_path'
        from /usr/bin/ronn:23:in `<main>'
/usr/lib/ruby/3.0.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'mini_portile2' (~> 2.5.0) - did find: [mini_portile2-2.6.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/build/.local/share/gem/ruby/3.0.0:/usr/lib/ruby/gems/3.0.0' , execute `gem env` for more information
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1402:in `block in activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1390:in `each'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1390:in `activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1372:in `activate'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1408:in `block in activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1390:in `each'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1390:in `activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1372:in `activate'
        from /usr/lib/ruby/3.0.0/rubygems.rb:302:in `block in activate_bin_path'
        from /usr/lib/ruby/3.0.0/rubygems.rb:301:in `synchronize'
        from /usr/lib/ruby/3.0.0/rubygems.rb:301:in `activate_bin_path'
        from /usr/bin/ronn:23:in `<main>'
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /home/ghost/chroot/ghost/build
````
````
~/.aur/booster-git ⑂master* $ pqs portile2
local/ruby-mini_portile2 2.6.1-1
    Simple autoconf builder for developers
                                                                                                                                                                                               [ 0s | 10.06:04:22 ]
~/.aur/booster-git ⑂master* $ pactree -d 2 ruby-ronn-ng
ruby-ronn-ng
├─ruby
│ ├─gdbm
│ ├─openssl
│ ├─libffi
│ ├─libyaml
│ ├─gmp
│ ├─zlib
│ ├─rubygems
│ └─ruby-irb
├─ruby-hpricot
│ └─ruby
├─ruby-rdiscount
│ └─ruby
├─ruby-mustache
│ └─ruby
├─ruby-kramdown
│ ├─ruby
│ └─ruby-rexml
└─ruby-nokogiri
  ├─ruby
  ├─ruby-mini_portile2
  └─libxslt
````

**Comment by anatol** [comment]
Fixed with ruby-nokogiri-1.11.7-2 that is pushed to stable repos.
